/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaswingapp;

import crudmysql.gui.addClientFrame;
import crudmysql.Client.Dao.DaoClient;
import crudmysql.Client.Dao.DaoOffreClient;
import crudmysql.Client.gui.model.TableClientModel;
import crudmysql.beans.Client;
import crudmysql.beans.Depense;
import crudmysql.beans.Offre;
import crudmysql.gui.infoClientFrame;
import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mathishoulet
 */
public class Accueil extends javax.swing.JFrame {

    private ArrayList<Client> clients;
    private DefaultListModel model = new DefaultListModel();
    private TableClientModel model_table;
    private JTable table;
    private JButton cardClientBtn;
    private String[] valueTable=new String[6];
    private String id;
    private String revenu;
    private String nom;
    private String prenom;
    private String age;
    private String perso;
    public String idfamille;
    private String pro;
    private Client newClient;
    private Offre newOffre;
    private Depense newDepense;

    /**
     * Creates new form Accueil
     */
    public Accueil(ArrayList<Client> clients) {
        super();
        setTitle("Online Prospect - BETA");
        this.setSize(500, 300);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        this.clients = clients;
        initComponents();
        modifComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1920, 130);

        jPanel3.setBackground(new java.awt.Color(87, 155, 170));

        jButton1.setText("jButton1");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("jButton1");
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton1");
        jButton3.setBorder(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(57, 57, 57)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 130, 240, 950);

        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(310, 270, 890, 400);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 140, 1020, 80);

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(310, 230, 73, 23);

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(980, 230, 73, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int rowIndex = jTable1.getSelectedRow();
        for (int k = 0; k <= 7; k++) {
            Object item = jTable1.getModel().getValueAt(rowIndex, k);
       
            if(k==0){
                id= item.toString();
            }else if(k==1){
                nom= item.toString();
            }else if(k==2){
                prenom= item.toString();
            }else if(k==3){
                age= item.toString();
            }else if(k==4){
                pro= item.toString();
            }else if(k==5){
                perso= item.toString();
            }else if(k==6){
                revenu= item.toString();
            }else if(k==7){
                idfamille=item.toString();
            }

        }

        if(rowIndex>0){
         try {
            Offre offres = DaoOffreClient.getOffreClientDao().getSouscription(idfamille);
            infoClientFrame dd = new infoClientFrame(id,nom,prenom,age,perso,pro,revenu,idfamille,offres);
            dd.setVisible(true);
            
            System.out.println("souscription"+offres);
            
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);

        }
        }
        

        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            addClientFrame ddg = new addClientFrame(getThis());
          ddg.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed
    
    public Accueil getThis(){
        return this;
    }
    public void modifComponents() {

        jLabel2.setText("Bienvenue [prenom de l'utilisateur]");
        jLabel2.setFont(new Font("MARKET DECO", Font.PLAIN, 30));
        jLabel2.setForeground(Color.white);
        jLabel3.setText("categories");
        jLabel3.setFont(new Font("MARKET DECO", Font.PLAIN, 30));
        jLabel3.setForeground(Color.white);
        jButton1.setText("     clients");
        jButton1.setFont(new Font("MARKET DECO", Font.PLAIN, 22));
        jButton1.setOpaque(false);
        jButton1.setBorder(null);
        jButton1.setForeground(Color.white);
        jButton2.setText("     Produits");
        jButton2.setFont(new Font("MARKET DECO", Font.PLAIN, 22));
        jButton2.setOpaque(false);
        jButton2.setBorder(null);
        jButton2.setForeground(Color.white);
        jButton3.setText("  Mon compte");
        jButton3.setFont(new Font("MARKET DECO", Font.PLAIN, 22));
        jButton3.setOpaque(false);
        jButton3.setBorder(null);
        jButton3.setForeground(Color.white);
        jButton4.setText("Détails");
        jButton5.setText("Ajouter un client");

        model_table = new TableClientModel();

        jTable1.setModel(model_table);
        jTable1.setBackground(Color.white);

        jLabel4.setText("Clients");
        jLabel4.setFont(new Font("MARKET DECO", Font.PLAIN, 50));
        jLabel4.setForeground(new Color(87, 155, 170));

    }
      public Client getNewClient() {
        return newClient;
    }

    public void setNewClient(Client newClient) {
        System.out.println("Client passé en paramètre "+newClient);
        this.newClient = newClient;
    }
        
    public Offre getNewOffreClient() {
        return newOffre;
    }

    public void setNewOffreClient(Offre newOffre) {
        System.out.println("Offre passé en paramètre "+newOffre);
        this.newOffre = newOffre;
    }
    
    public Depense getNewDepenseClient() {
        return newDepense;
    }

    public void setNewDepenseClient(Depense newDepense) {
        System.out.println("Depense passé en paramètre "+newDepense);
        this.newDepense = newDepense;
    }
       public void refresh(){
        try {
            clients = DaoClient.getClientDao().getAll();
            model.addElement(clients.get(clients.size()-1));
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
